---
# Bring stack down
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped
    - name: wait for port 80 to stop/drain
      wait_for: port=80 state=drained

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: stop apache2
      service: name=apache2 state=stopped
    - name: wait for port 80 to stop
      wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - name: restart mysql
      service: name=mysql state=restarted
    - name: wait for port 3306 to respond
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306

# Bring stack up
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: start apache2
      service: name=apache2 state=started
    - name: wait for port 80 to respond
      wait_for: port=80

- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: start nginx
      service: name=nginx state=started
    - name: wait for port 80 to respond
      wait_for: port=80
